# Generated by Django 3.1.7 on 2021-07-07 08:03

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', multiselectfield.db.fields.MultiSelectField(choices=[('Hatchback', 'Hatchback'), ('Sedan', 'Sedan'), ('SUV', 'SUV'), ('SUV', 'Luxury')], max_length=23, verbose_name='Category')),
                ('company', models.CharField(default=None, max_length=156, verbose_name='Company')),
                ('name', models.CharField(max_length=156, verbose_name='Name')),
                ('model_year', multiselectfield.db.fields.MultiSelectField(choices=[('2010-2012', '2010-2012'), ('2013-2016', '2013-2016'), ('2017-2019', '2017-2019'), ('2020-2021', '2020-2021')], max_length=39, verbose_name='Model')),
                ('transmission_type', multiselectfield.db.fields.MultiSelectField(choices=[('Automatic', 'Automatict'), ('Manual', 'Manual')], max_length=16, verbose_name='Transmission')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('detail', models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='Description')),
                ('inventory', models.IntegerField(default=None, verbose_name='Stock')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='cars', verbose_name='Image1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='cars', verbose_name='Image2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='cars', verbose_name='Image3')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='cars', verbose_name='Image4')),
            ],
        ),
    ]
