# Generated by Django 3.1.7 on 2021-07-07 08:15

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetail',
            name='transmission_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=16, verbose_name='Transmission'),
        ),
    ]
