# Generated by Django 3.1.7 on 2021-07-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20210707_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetail',
            name='image1',
            field=models.ImageField(blank=True, height_field='150px', null=True, upload_to='cars', verbose_name='Image1', width_field='150px'),
        ),
    ]
