# Generated by Django 3.1.7 on 2021-07-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20210707_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetail',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='cars', verbose_name='Image1'),
        ),
    ]
