# Generated by Django 3.1.7 on 2021-07-07 11:50

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20210707_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetail',
            name='car_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Hatchback', 'Hatchback'), ('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Luxury', 'Luxury')], max_length=26, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='cardetail',
            name='price',
            field=models.FloatField(verbose_name='Price'),
        ),
    ]
