# Generated by Django 3.1.7 on 2021-07-09 06:28

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20210707_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardetail',
            name='Fuel_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('CNG', 'CNG'), ('Electric', 'Electric')], max_length=26, null=True, verbose_name='Fuel'),
        ),
        migrations.AlterField(
            model_name='cardetail',
            name='price',
            field=models.FloatField(verbose_name='Price (in lakhs)'),
        ),
    ]
