# Generated by Django 3.1.7 on 2021-07-09 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_auto_20210709_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardetail',
            old_name='Fuel_type',
            new_name='fuel_type',
        ),
    ]
